#!/usr/bin/env bash

#AUTHOR: Brad West
#---
#DESCRIPTION: Mutation testing of 4 graph algorithms. The algorithms
#  are:
#
#    1. Depth First Search
#    2. Breadth First Search
#    3. Minimum Spanning Tree (Prim's Algorithm)
#    4. Minimum Spanning Tree (Kruskal's Algorithm)
#
#In the package networkx, these algorithms are implemented within the
#following modules:
#
#    1. networkx.algorithms.traversal.edgedfs
#    2. networkx.algorithms.traversal.edgebfs
#    3. networkx.algorithms.tree.mst
#    4. networkx.algorithms.tree.mst
#
#We mutate these specific methods and run them against our pseudo-oracle
#generated by metamorphic testing.

mut.py --target networkx.algorithms.traversal.edgedfs --unit-test src.test_algos